[2025-10-25T00:12:39.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T00:12:39.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: support_ticket_pipeline.extract_tickets manual__2025-10-25T00:12:27.177991+00:00 [queued]>
[2025-10-25T00:12:39.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: support_ticket_pipeline.extract_tickets manual__2025-10-25T00:12:27.177991+00:00 [queued]>
[2025-10-25T00:12:39.130+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-25T00:12:39.135+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_tickets> on 2025-10-25 00:12:27.177991+00:00
[2025-10-25T00:12:39.152+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'support_ticket_pipeline', 'extract_tickets', 'manual__2025-10-25T00:12:27.177991+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/support_ticket_pipeline.py', '--cfg-path', '/tmp/tmp_kv5q9bs']
[2025-10-25T00:12:39.163+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract_tickets
[2025-10-25T00:12:39.165+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=38) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-25T00:12:39.167+0000] {standard_task_runner.py:64} INFO - Started process 47 to run task
[2025-10-25T00:12:39.278+0000] {task_command.py:426} INFO - Running <TaskInstance: support_ticket_pipeline.extract_tickets manual__2025-10-25T00:12:27.177991+00:00 [running]> on host 492540b58c3b
[2025-10-25T00:12:39.432+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='support_ticket_pipeline' AIRFLOW_CTX_TASK_ID='extract_tickets' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T00:12:27.177991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T00:12:27.177991+00:00'
[2025-10-25T00:12:39.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T00:12:39.441+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T00:12:39.442+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/support_ticket_pipeline.py", line 46, in extract_tickets
    raise FileNotFoundError(f"Expected raw CSV at {RAW_CSV}.")
FileNotFoundError: Expected raw CSV at /opt/***/data/raw/tickets.csv.
[2025-10-25T00:12:39.467+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=support_ticket_pipeline, task_id=extract_tickets, run_id=manual__2025-10-25T00:12:27.177991+00:00, execution_date=20251025T001227, start_date=20251025T001239, end_date=20251025T001239
[2025-10-25T00:12:39.476+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract_tickets (Expected raw CSV at /opt/***/data/raw/tickets.csv.; 47)
[2025-10-25T00:12:39.483+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T00:12:39.498+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T00:12:39.499+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
