[2025-10-25T01:18:35.302+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T01:18:35.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: support_ticket_pipeline.generate_embeddings manual__2025-10-25T01:17:45.133659+00:00 [queued]>
[2025-10-25T01:18:35.377+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: support_ticket_pipeline.generate_embeddings manual__2025-10-25T01:17:45.133659+00:00 [queued]>
[2025-10-25T01:18:35.378+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-25T01:18:35.408+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): generate_embeddings> on 2025-10-25 01:17:45.133659+00:00
[2025-10-25T01:18:35.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'support_ticket_pipeline', 'generate_embeddings', 'manual__2025-10-25T01:17:45.133659+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/support_ticket_pipeline.py', '--cfg-path', '/tmp/tmp5mwadyrh']
[2025-10-25T01:18:35.446+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-25T01:18:35.447+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask generate_embeddings
[2025-10-25T01:18:35.447+0000] {standard_task_runner.py:64} INFO - Started process 82 to run task
[2025-10-25T01:18:35.603+0000] {task_command.py:426} INFO - Running <TaskInstance: support_ticket_pipeline.generate_embeddings manual__2025-10-25T01:17:45.133659+00:00 [running]> on host 64eb31e1f688
[2025-10-25T01:18:35.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='support_ticket_pipeline' AIRFLOW_CTX_TASK_ID='generate_embeddings' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T01:17:45.133659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T01:17:45.133659+00:00'
[2025-10-25T01:18:35.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T01:18:35.877+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T01:18:35.879+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/support_ticket_pipeline.py", line 97, in generate_embeddings
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
[2025-10-25T01:18:35.911+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=support_ticket_pipeline, task_id=generate_embeddings, run_id=manual__2025-10-25T01:17:45.133659+00:00, execution_date=20251025T011745, start_date=20251025T011835, end_date=20251025T011835
[2025-10-25T01:18:35.952+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task generate_embeddings (No module named 'sentence_transformers'; 82)
[2025-10-25T01:18:35.979+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T01:18:36.065+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T01:18:36.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
